### PR TITLE
Add space in log between each backup

### PR DESCRIPTION
**Pull request by lapineige**
This increases readability of the log (received by email) by separating each block.
It allows for a quick visual scan of the content.

### CODE REVIEW

**Comment by lapineige** [comment]
Thank you for merging :)

**Comment by lapineige** [comment]
Could you also publish a new tag ? It for updating the app.

Or maybe wait for #14 ?

**Comment by mcrudelis** [comment]
Best to merge #14 before indeed, but there's conflicts to solve before.
I keep the tab open to take care of it as soon as I can ;)

**Comment by mcrudelis** [comment]
Well, it's done ;)
https://github.com/mcrudelis/archivist/releases/tag/v1.3.4

**Comment by lapineige** [comment]
And it's lovely :D

Thank you very much :)

**Pull request merged**
